### PR TITLE
Title changes

### PR DESCRIPTION
**Pull request by karenword**
This PR responds to comments that 2-part titles are difficult to work with, making the following changes:

How Learning Works: The Importance of Practice -> Skill and Practice
How Learning Works: Expertise and Instruction -> Expertise and Instruction
How Learning Works: Working Memory and Cognitive Load -> Working Memory and Cognitive Load
Building Teaching Skill: Getting Feedback -> Building Skill with Feedback
Creating a Positive Learning Environment: Motivation and Demotivation -> Motivation and Demotivation
Creating a Positive Learning Environment: Mindset -> Mindset
Building Teaching Skill: The Importance of Practice -> Teaching is a Skill
Building Teaching Skill: Live Coding -> Live Coding is a Skill
Building Teaching Skill: Lesson Study -> Lesson Study
Building Teaching Skill: Performance Revised -> Live Coding Round II
(New section: Managing a Diverse Classroom)
The Carpentries: How We Operate -> no change
The Carpentries: Workshop Introductions -> Workshop Introductions 
The Carpentries: Teaching Practices -> Putting It Together
(New section: Checkout Process)
Afternoon Wrap-Up -> Wrapping Up

### CODE REVIEW

**Comment by laufers** [comment]
Can the area portion of the titles be kept as a tag or part of the objectives?

**Comment by anenadic** [comment]
Building Teaching Skill: The Importance of Practice -> Teaching is a Skill from @karenword maybe "Teaching is a Learned Skill" and also "Live Coding is a Learned Skill"

**Comment by alex-konovalov** [comment]
One could also find useful to have a more readable list without former titles:
* Skill and Practice
* Expertise and Instruction
* Working Memory and Cognitive Load
* Building Skill with Feedback
* Motivation and Demotivation
* Mindset
* Teaching is a Skill
* Live Coding is a Skill
* Lesson Study
* Live Coding Round II
* Managing a Diverse Classroom
* The Carpentries: How We Operate
* Workshop Introductions
* Putting It Together
* Checkout Process
* Wrapping Up

**Comment by alex-konovalov** [comment]
+1 to "learned skill" as @anenadic suggests.  Also, the list repeat "skill" 4 times. Maybe, the first two usages of this word can be eliminated? I am happy with the old "The Importance of Practice" and  "Getting Feedback" titles.

**Comment by anenadic** [comment]
+1 for shorter titles from @karenword

**Comment by amyehodge** [comment]
I thought that changes had been made to the working memory and cognitive load lesson so that we avoided the fluid representation issue (working/short-term and persistent/long-term), but I'm not seeing those changes reflected in this repo. I mention it because I was going to suggest that we change the title of that session to reflect those changes, so to either "memory and cognitive load" or "short-term memory and cognitive load," because I thought that "short-term" was the term chosen for that. I must be getting things confused here.

**Comment by amyehodge** [comment]
Instead of Lesson Study, I prefer "Preparing to Teach" -- I think "lesson study" is harder to understand

**Comment by anenadic** [comment]
Also "Lesson Study" does not talks much about the original Japanese Lesson Study any more.

**Comment by raynamharris** [comment]
To keep the spirit of themes, I would make a brief overview table on the index

| Time  | Theme | 
| ----  | ---- | 
| Day 1 AM | How Learning Works |   
| Day 1 PM | Creating a Positive Learning Environment | 
| Day 2 AM | Building Teaching Skill | 
| Day 2 PM | The Carpentries |

**Comment by anenadic** [comment]
> To keep the spirit of themes, I would make a brief overview table on the index
> 
> Time	Theme
> Day 1 AM	How Learning Works
> Day 1 PM	Creating a Positive Learning Environment
> Day 2 AM	Building Teaching Skill
> Day 2 PM	The Carpentries

+1

**Comment by raynamharris** [comment]
There was a conflict with the title of the memory lesson, so I resolved it.

**Comment by raynamharris** [comment]
There was a conflict with the live coding lesson so I resolved it. Even though we have changed much of the language in our live coding section to use the phrases "code along" and "participatory live coding", I am still a fan of @karenword's suggested title of "Live coding is a skill".

**Comment by raynamharris** [comment]
@amyehodge , as per your comment: 

> I thought that changes had been made to the working memory and cognitive load lesson so that we avoided the fluid representation issue (working/short-term and persistent/long-term), but I'm not seeing those changes reflected in this repo. I mention it because I was going to suggest that we change the title of that session to reflect those changes, so to either "memory and cognitive load" or "short-term memory and cognitive load," because I thought that "short-term" was the term chosen for that. I must be getting things confused here.

We did make those changes in the original but perhaps happened after this repo was forked. However, you point is noted that we shouldn't use "working in the title". I think "Memory and Cognitive load would be the best title option.

**Comment by raynamharris** [comment]
This is my attempt to that most suggested titles haven't received any objection (normal formatting) but a few have sparked discussion (bold). Here I've listed the proposed and suggested title. @alex-konovalov, I have keep the 1st, 3rd, and 4th occurrence of skill, but I do suggestion a modification of the 2nd. Let me know if you like it

1. **Skill and Practice --> Building Skill with Practice**
2. Expertise and Instruction
3. **Working Memory and Cognitive Load --> Memory and Cognitive Load**
4. **Building Skill with Feedback --> "Giving and Receiving Feedback"**
5. Motivation and Demotivation
6. Mindset
7. Teaching is a Skill
8. Live Coding is a Skill
9. **Lesson Study --> Preparing to Teach**
10. Live Coding Round II
11. Managing a Diverse Classroom
12. The Carpentries: How We Operate
13. Workshop Introductions
14. Putting It Together
15. Checkout Process
16. Wrapping Up

**Comment by raynamharris** [comment]
I have one more suggestion. "Teaching is a Skill" seems very vague to me. This lesson is about growth mindset and the art of feedback. Since the first mindset-related episode is about student mindset and the second is about the teacher's mindset, how about this:


- **Mindset --> The Learner's Mindset**
- **Teaching is a Skill --> The Instructor's Mindset**

**Comment by raynamharris** [comment]
@ChristinaLK. Did you mean to close this? If so, what was the rationale and where will the discussion of titles be picked up again?

**Comment by alex-konovalov** [comment]
@raynamharris "Collecting Student Feedback" looks good. Do we prefer the term "Learners" over "Students" though, or both are fine?

**Comment by karenword** [comment]
Apologies @raynamharris and all as it sounds like we were unclear about the intent and the timeline of this discussion. These changes along with others discussed at the last meeting were intended to be included in the current set of updates, which we delayed merging with the curriculum until today (we had indicated that changes would be merged around the 10th). Earlier today @ChristinaLK and I met and read through all existing comments, changed the titles based on comments that were here at that time, and merged with the rest of the changes to the main repository in a separate PR. These are by no means final, and further discussion can take place via issues or PRs on the main repository.

We will now be giving data-lessons a rest for a while until the next round of substantial changes. 

Sorry about the confusion!

**Pull request closed without merging**
