### PR TITLE
lesson study overhaul

### PR DESCRIPTION
**Pull request by karenword**
~~This PR is *not finished yet* but I'm starting the PR so @ChristinaLK can see where this is headed & comment accordingly!~~
Ready to merge or can update with proposed reorder/other edits first.

### CODE REVIEW

**Comment by karenword** [comment]
Getting closer -- @ChristinaLK do you think we can find a way to put the PNG image from the linked page on Bloom's (https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/) into Lesson Study? CC licensing but not SVG format.

**Comment by ChristinaLK** [comment]
That order sounds good to me!  Looking at changes in a min.

**Comment by ChristinaLK** [comment]
😍 
AMAZING.

**Comment by ChristinaLK** [comment]
merge this?

**Comment by karenword** [comment]
Wait 10 min and I will add the re-order & expand a few time estimates?

**Comment by karenword** [comment]
OR I'll add those separately! Thanks!! :)

**Pull request merged**
